### ISSUE TITLE
Nsis header and sidebar images not present in installer

### ISSUE THREAD

**Issue by tigerros** [crabnebula-dev/cargo-packager#111]
`Cargo.toml`:

```toml
[package.metadata.packager]
before-packaging-command = "cargo build --release"
identifier = "com.acme.foo"
product-name = "Foo"
formats = ["nsis"]
resources = [
    { src = "assets/icons/*", target = "assets/icons" },
    { src = "assets/nsis/*", target = "assets/nsis" },
]
icons = [
    "assets/icons/32x32.png",
    "assets/icons/128x128.png",
    "assets/icons/icon.ico",
]

[package.metadata.package.nsis]
installer_icon = "assets/icons/icon.ico"
header_image = "assets/nsis/header.bmp"
sidebar_image = "assets/nsis/sidebar.bmp"
install_mode = "CurrentUser"
appdata_paths = ["$LOCALAPPDATA/$PUBLISHER/$PRODUCTNAME"]
```

The images: [nsis.zip](https://github.com/crabnebula-dev/cargo-packager/files/13721856/nsis.zip)

Installer screenshots:
![image](https://github.com/crabnebula-dev/cargo-packager/assets/76173380/1bdf4a77-52ee-4f0e-889d-86185979ce3b)
