### ISSUE TITLE
Add python example

### ISSUE THREAD

**Issue by rakeshksr** [crabnebula-dev/cargo-packager#231]
`cargo-packager` working well with python projects with combination of `pyinstaller`.
Adding python example will significantly benefit to python developers for packaging their python projects.

**Comment by naman-crabnebula** [comment]
Hi @rakeshksr , I don't think we are currently planning to add Python support to the Cargo Packager. 

Thank You

**Comment by thewh1teagle** [comment]
I'm interested in the same thing. If it has beforePackageCommand, all we need is to point the packager to execute the right exe in the right location. it would be awesome to add example for it or at least some inputs here.

**Comment by rakeshksr** [comment]
@thewh1teagle, `Packager.toml` of my python project 
```toml
name = "<project name>"
product-name = "<Long Name>"
version = "1.0.0"
authors = ["<author name>"]
publisher = "<publisher name>"
binaries = [{ path = "<main binary path>", main = true }]
identifier = "com.project.name"
before-packaging-command = "pyinstaller --clean --onefile --windowed --name <name> --add-data src/<name>/assets:assets --icon src/<name>/assets/app_icon.png src/<name>/__main__.py"
out-dir = "dist/bin"
binaries-dir = "dist"
icons = ["src/<name>/assets/app_icon.png"]
```
